M48
; DRILL file {KiCad 7.0.1} date Mon 15 May 2023 20:45:33 CEST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-05-15T20:45:33+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1575
%
G90
G05
T1
X2.2362Y-3.2618
X3.8583Y-3.2638
T2
X3.0555Y-1.776
T0
M30
